Name:           cbench
Version:        2.0.0
Release:        1%{?dist}
Summary:        Cbench HPC benchmarking framework — Python toolchain
License:        GPLv2
URL:            https://github.com/cdmaestas/cbench
BuildArch:      noarch

BuildRequires:  python3-pip

# Runtime: use distro-provided Python packages rather than bundling.
# For RHEL/Rocky 8+: dnf install python3-click python3-pyyaml python3-rich
#                                  python3-jinja2 python3-jsonschema
# Flask (web dashboard) is optional — install separately if needed.
Requires:       python3 >= 3.9
Requires:       python3-click >= 8.1
Requires:       python3-pyyaml >= 6.0
Requires:       python3-rich >= 13.0
Requires:       python3-jinja2 >= 3.1
Requires:       python3-jsonschema >= 4.0

# MPI: needed to build and run MPI benchmarks (IOR, mdtest, IMB, OSU, HPL, ...).
# Weak dependency on purpose: installed by default (dnf install_weak_deps), but
# sites standardized on another MPI (Intel MPI, MPICH, HPE MPT, Cray via
# modules) can skip it. RHEL installs Open MPI outside PATH (/usr/lib64/openmpi):
#   module load mpi/openmpi-x86_64     (needs environment-modules), or
#   export PATH=/usr/lib64/openmpi/bin:$PATH
# environment-modules provides the `module` command; sites on Lmod already have
# one, and dnf skips a weak dep that conflicts rather than failing the install.
# Keep in sync with debian/control Recommends and the Makefile fpm targets.
Recommends:     openmpi-devel
Recommends:     environment-modules
# fio: the default node-local IOPS/metadata test (snb fio, iometadata_fio).
# RHEL/Rocky AppStream and Fedora ship it as `fio`; cbench can also build it.
Recommends:     fio

# Optional: web dashboard
# Requires:     python3-flask >= 2.0

%description
Cbench is an HPC benchmarking framework originally developed at Sandia
National Laboratories. The Python toolchain (v2.0) provides a cbench
CLI for the full benchmark lifecycle: build benchmark software, generate
job scripts, submit to a batch scheduler, parse output, query results,
run single-node benchmarks, and serve a web dashboard.

Open MPI is recommended (not required) for building and running the MPI
benchmarks. RHEL installs it outside PATH: `module load mpi/openmpi-x86_64`
(environment-modules, also recommended) or add /usr/lib64/openmpi/bin to
PATH. fio is recommended for the node-local I/O tests. Sites using another
MPI can install with --setopt=install_weak_deps=False.

%install
# Install cbench package only (no bundled deps — distro packages handle them)
install -d %{buildroot}/usr/lib/cbench
pip3 install --quiet --no-deps \
    --target %{buildroot}/usr/lib/cbench \
    %{cbench_srcdir}

# Strip buildroot prefix from any embedded paths
find %{buildroot}/usr/lib/cbench -name "*.py" \
    -exec sed -i "s|%{buildroot}||g" {} \; 2>/dev/null || true

# Wrapper script
install -D -m 755 %{cbench_pkgdir}/cbench.wrapper %{buildroot}/usr/bin/cbench

# Man pages (pre-generated by `make man` in packaging/)
%define manstage %{cbench_pkgdir}_stage
if [ -d %{manstage}/usr/share/man/man1 ]; then
    install -d %{buildroot}/usr/share/man/man1
    install -m 644 %{manstage}/usr/share/man/man1/*.1.gz \
        %{buildroot}/usr/share/man/man1/
else
    echo "Warning: man pages not pre-generated. Run 'make man' first." >&2
fi

# Docs
install -D -m 644 %{cbench_repodir}/README.md   %{buildroot}/usr/share/doc/cbench/README.md
install -D -m 644 %{cbench_repodir}/CHANGELOG.md %{buildroot}/usr/share/doc/cbench/CHANGELOG.md

%files
/usr/lib/cbench/
/usr/bin/cbench
%doc /usr/share/doc/cbench/README.md
%doc /usr/share/doc/cbench/CHANGELOG.md
%if %(test -d %{manstage}/usr/share/man/man1 && echo 1 || echo 0)
/usr/share/man/man1/cbench*.1.gz
%endif

%changelog
* Fri Jul 03 2026 cdmaestas <12300246+cdmaestas@users.noreply.github.com> - 2.0.0-1
- Initial v2.0 package release.
- Python toolchain with build/gen-jobs/start-jobs/parse/query/snb/serve.
- Man pages generated from Click CLI via click-man.
