Name:           cbench
Version:        2.0.0
Release:        1%{?dist}
Summary:        Cbench HPC benchmarking framework — Python toolchain
License:        GPLv2
URL:            https://github.com/cdmaestas/cbench
BuildArch:      noarch

BuildRequires:  python3-pip

# Runtime: use distro-provided Python packages rather than bundling.
# For RHEL/Rocky 8+: dnf install python3-click python3-pyyaml python3-rich
#                                  python3-jinja2 python3-jsonschema
# Flask (web dashboard) is optional — install separately if needed.
Requires:       python3 >= 3.9
Requires:       python3-click >= 8.1
Requires:       python3-pyyaml >= 6.0
Requires:       python3-rich >= 13.0
Requires:       python3-jinja2 >= 3.1
Requires:       python3-jsonschema >= 4.0

# Optional: web dashboard
# Requires:     python3-flask >= 2.0

%description
Cbench is an HPC benchmarking framework originally developed at Sandia
National Laboratories. The Python toolchain (v2.0) provides a cbench
CLI for the full benchmark lifecycle: build benchmark software, generate
job scripts, submit to a batch scheduler, parse output, query results,
run single-node benchmarks, and serve a web dashboard.

%install
# Install cbench package only (no bundled deps — distro packages handle them)
install -d %{buildroot}/usr/lib/cbench
pip3 install --quiet --no-deps \
    --target %{buildroot}/usr/lib/cbench \
    %{cbench_srcdir}

# Strip buildroot prefix from any embedded paths
find %{buildroot}/usr/lib/cbench -name "*.py" \
    -exec sed -i "s|%{buildroot}||g" {} \; 2>/dev/null || true

# Wrapper script
install -D -m 755 %{cbench_pkgdir}/cbench.wrapper %{buildroot}/usr/bin/cbench

# Man pages (pre-generated by `make man` in packaging/)
%define manstage %{cbench_pkgdir}_stage
if [ -d %{manstage}/usr/share/man/man1 ]; then
    install -d %{buildroot}/usr/share/man/man1
    install -m 644 %{manstage}/usr/share/man/man1/*.1.gz \
        %{buildroot}/usr/share/man/man1/
else
    echo "Warning: man pages not pre-generated. Run 'make man' first." >&2
fi

# Docs
install -D -m 644 %{cbench_repodir}/README.md   %{buildroot}/usr/share/doc/cbench/README.md
install -D -m 644 %{cbench_repodir}/CHANGELOG.md %{buildroot}/usr/share/doc/cbench/CHANGELOG.md

%files
/usr/lib/cbench/
/usr/bin/cbench
%doc /usr/share/doc/cbench/README.md
%doc /usr/share/doc/cbench/CHANGELOG.md
%if %(test -d %{manstage}/usr/share/man/man1 && echo 1 || echo 0)
/usr/share/man/man1/cbench*.1.gz
%endif

%changelog
* Thu Jul 03 2026 cdmaestas <cdmaestas@gmail.com> - 2.0.0-1
- Initial v2.0 package release.
- Python toolchain with build/gen-jobs/start-jobs/parse/query/snb/serve.
- Man pages generated from Click CLI via click-man.
